Add Register iterator
icedland/iced pull request #138
Opened 2021-01-22 23:30 UTC by tnballo

Implements preferred solution to #136.

2021-01-23 00:19 UTC, tnballo commented
Hmm...got 7 CI errors for files I did not modify in 8f3ce3f. Fixed those in 4a9a081, another 10 errors crop up - again for files unrelated to the change I want to make. Guessing this is due to a version increase for the Rust toolchain since the last time a PR was issued.

Should I fix all errors? They look uncontroversial but are outside the scope of this PR.

2021-01-23 07:25 UTC, 0xd4d requested changes

2021-01-23 07:25 UTC, 0xd4d commented on src/rust/iced-x86/src/register.rs
> +	}
Add a newline here

2021-01-23 07:25 UTC, 0xd4d commented
Yes, undo that last commit (clippy fixes), I'll just test it locally.

Also move the register iterator to register.rs.

2021-01-23 15:04 UTC, 0xd4d commented on src/rust/iced-x86/src/register_iterator.rs
> +	pub fn new() -> Self {
This doesn't need to be public. Users should always call `Register::values()` to get the iterator.

2021-01-23 15:48 UTC, 0xd4d commented
I've pushed the clippy fixes to master so if you rebase, the CI should (hopefully) pass.

2021-01-23 19:17 UTC, tnballo commented
Thanks! Reverted the clippy commit, re-based on master, and made the review changes. Only 2 CI errors this time (subset of the revert).

2021-01-23 19:45 UTC, tnballo commented
Those 2 CI errors were my mistake with git workflows - PR is now a single file change (`register.rs`). Looks like Rust CI passed but Python had an issue downloading dependencies.

2021-01-23 20:34 UTC, 0xd4d approved these changes
Yeah it's a network error, I've seen it happen before:

"warning: spurious network error (2 tries remaining): error inflating zlib stream; class=Zlib (5)"

2021-01-23 20:36 UTC, merged

2021-01-23 20:38 UTC, 0xd4d commented
Thanks, it's merged now!

BTW, the `Register` enum uses names `R8L` - `R15L` but most assemblers use the names `R8B`-`R15B`, so you might need to special case those regs in xgadget in case the users use `r8b`.

2021-01-24 22:29 UTC, tnballo commented
Thanks for the heads up. With the hashmap logic you suggested in #136 it'll be quite convenient to add a 2nd key for those registers and then accept inputs case-insensitive :+1:

2021-02-04 21:40 UTC, wtfsck commented
@tnballo Let me know if you need it pushed to crates.io and I'll release 1.10.3.

2021-02-05 23:41 UTC, tnballo commented
Yup, if you could push to crates.io soon I'd appreciate it!

2021-02-06 11:43 UTC, wtfsck commented
It's now on crates.io. I had to cherry-pick your commit and a few more since the master branch requires 1.42.0 but 1.10.x must support 1.20.0.

2021-02-06 13:48 UTC, tnballo commented
Awesome, thanks!