Made CodeAssembler traits public
icedland/iced pull request #236
Opened 2021-12-04 16:53 UTC by Kixiron

Closes #231

2021-12-05 13:35 UTC, wtfsck commented
Build failed, see https://github.com/icedland/iced/runs/4422431957?check_suite_focus=true

2021-12-06 06:07 UTC, wtfsck requested changes
Build failed.

You've also accidentally committed some binary files.

2021-12-06 16:17 UTC, wtfsck commented
Yes, you can ignore them.

I noticed you renamed the module. This will possibly cause problems with the docs. It's possible that all the generated methods will be shown first. See [docs here](https://docs.rs/iced-x86/1.15.0/iced_x86/code_asm/struct.CodeAssembler.html) where eg. the constructor is at the top of the file (after the module docs) and all the generated methods are at the end.

Is the order still the same or are all generated methods at the top now?

2021-12-06 16:43 UTC, Kixiron commented
It looks to be the same in terms of method layout
![image](https://user-images.githubusercontent.com/25047011/144886282-6face2af-746e-4664-88a8-176516415ea6.png)

2021-12-06 16:45 UTC, Kixiron commented
I'm getting this warning from rustdoc but I'm not sure what version of rust it's from vs. what versions of rust you support, would you like me to fix it?
```rust
warning: lint `invalid_html_tags` has been renamed to `rustdoc::invalid_html_tags`
  --> iced-x86\src\lib.rs:13:9
   |
13 | #![warn(invalid_html_tags)]
   |         ^^^^^^^^^^^^^^^^^ help: use the new name: `rustdoc::invalid_html_tags`
   |
   = note: `#[warn(renamed_and_removed_lints)]` on by default
```

2021-12-06 17:01 UTC, wtfsck commented
You can ignore that warning. We need to support rust 1.48.0 and it doesn't support the new lint name.

2021-12-06 17:05 UTC, Kixiron commented
I added trait documentation to the generator and ran it, but it seems to have changed a bunch of files from LF to CRLF, do you know how to fix that?

2021-12-06 17:19 UTC, wtfsck commented
Docs aren't needed, a simple doc(hidden) at the top should be enough.

Maybe you didn't enable the git option to use default line endings, I think it just checks out LF line endings when it should be checking out files with CRLF line endings. You should probably set `core.autocrlf` to `true`, see https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration . Reset the files and re-run the generator and it will hopefully work.

2021-12-12 13:53 UTC, wtfsck commented
Did it compile without any warnings/errors?

2021-12-14 17:03 UTC, Kixiron commented
Clippy gives missing inline warnings for all of the trait methods
```rust
warning: missing `#[inline]` for a method
     --> iced-x86\src\code_asm\fn_asm_impl.rs:74231:2
      |
74231 | /     fn vsqrtpd(&mut self, op0: AsmRegisterYmm, op1: AsmMemoryOperand) -> Result<(), IcedError> {
74232 | |         let code = if op1.is_broadcast() {
74233 | |             Code::EVEX_Vsqrtpd_ymm_k1z_ymmm256b64
74234 | |         } else if self.instruction_prefer_vex() {
...     |
74239 | |         self.add_instr_with_state(Instruction::with2(code, op0.register(), op1.to_memory_operand(self.bitness()))?, op0.state().merge(op1...
74240 | |     }
      | |_____^
      |
      = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#missing_inline_in_public_items
```
A bunch of tests have redundant closures
```rust
warning: redundant closure
   --> iced-x86\src\formatter\nasm\tests\mod.rs:127:57
    |
127 |     formatter_test_nondec(64, "Nasm", "NonDec_MemMinimum", || create_memminimum());
    |                                                            ^^^^^^^^^^^^^^^^^^^^^^ help: replace the closure with the function itself: `create_memminimum`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_closure

warning: `iced-x86` (lib test) generated 183 warnings
```
But my changes didn't cause these, what do you want me to do?

2021-12-14 21:05 UTC, wtfsck commented
Try this (`code_asm.rs`)

```diff
+#[allow(missing_docs)]
+#[allow(clippy::missing_errors_doc)]
+pub mod asm_traits;
 mod code_asm_methods;
+#[allow(clippy::missing_inline_in_public_items)]
 mod fn_asm_impl;
 mod fn_asm_pub;
-mod fn_asm_traits;
 mod mem;
 mod op_state;
 mod reg;
```
Notice that I removed `doc(hidden)` and added `allow(msising_docs)`

2021-12-15 04:10 UTC, Kixiron commented
Fixed all of the clippy warnings, should be good to go

2021-12-15 09:33 UTC, wtfsck requested changes
Can you undo the last commit? I fixed those earlier already, see https://github.com/icedland/iced/pull/239

Assuming everything builds, I'll merge this PR! Thanks!

2021-12-15 19:06 UTC, wtfsck approved these changes

2021-12-15 19:06 UTC, merged

2021-12-15 19:07 UTC, wtfsck commented
Thanks, merged!